services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    container_name: frontend
    # volumes:
    networks:
      - transcendence-network
    restart: no

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    container_name: backend
    volumes:
      - ./backend/app:/app
    networks:
      - transcendence-network
    restart: no

networks:
  transcendence-network:
    driver: bridge
