services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    # volumes:
    networks:
      - transcendence-network
    restart: unless-stopped

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    # volumes:
    networks:
      - transcendence-network
    restart: unless-stopped


networks:
  transcendence-network:
    driver: bridge
