services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    container_name: frontend
    volumes:
      - shared-data:/app
    networks:
      - transcendence-network
    restart: no

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "80:80"
    container_name: backend
    volumes:
      - shared-data:/app
    networks:
      - transcendence-network
    restart: no

networks:
  transcendence-network:
    driver: bridge

volumes:
  shared-data:
