DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL UNIQUE,
	email TEXT UNIQUE,
	password_hash TEXT,
	google_id TEXT UNIQUE,
	2fa_enable BOOLEAN,
	2fa_secret TEXT UNIQUE
);
